# Generated by Django 2.1.3 on 2019-01-03 13:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('is_collection', models.NullBooleanField(default=0, verbose_name='收藏状态')),
            ],
            options={
                'verbose_name': '博客收藏列表',
                'verbose_name_plural': '博客收藏列表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('content', tinymce.models.HTMLField(verbose_name='内容')),
                ('time', models.DateTimeField(auto_now_add=True, max_length=128, verbose_name='时间')),
                ('Prohibited', models.NullBooleanField(default=0, verbose_name='评论是否禁止查看')),
                ('Prohibited_info', models.CharField(default='', max_length=256, verbose_name='禁止信息')),
            ],
            options={
                'verbose_name': '博客评论列表',
                'verbose_name_plural': '博客评论列表',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('dynamic_like', models.IntegerField(blank=True, default=0, verbose_name='点赞次数')),
                ('dynamic_collection', models.IntegerField(blank=True, default=0, verbose_name='收藏次数')),
                ('dynamic_search', models.IntegerField(blank=True, default=0, verbose_name='搜索次数')),
            ],
            options={
                'verbose_name': '博客动态列表',
                'verbose_name_plural': '博客动态列表',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('is_like', models.NullBooleanField(default=0, verbose_name='点赞状态')),
            ],
            options={
                'verbose_name': '博客点赞列表',
                'verbose_name_plural': '博客点赞列表',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('title', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('content', tinymce.models.HTMLField(default='', verbose_name='内容')),
                ('data', models.DateField(auto_now_add=True, max_length=125, verbose_name='文章创建日期')),
                ('time', models.DateTimeField(auto_now_add=True, max_length=125, verbose_name='文章创建时间')),
                ('readnumber', models.IntegerField(default=0, verbose_name='文章阅读数量')),
                ('Prohibited', models.NullBooleanField(default=0, verbose_name='文章是否禁止查看')),
                ('Prohibited_info', models.CharField(default='', max_length=256, verbose_name='禁止信息')),
                ('last_time', models.DateTimeField(auto_now_add=True, max_length=125, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '博客文章列表',
                'verbose_name_plural': '博客文章列表',
            },
        ),
    ]
