# Generated by Django 2.1.3 on 2019-01-03 13:32

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.CharField(blank=True, default='/static/images/default.jpg', max_length=255, verbose_name='头像')),
                ('mobile', models.CharField(blank=True, default='', max_length=11, unique=True, verbose_name='手机号码')),
                ('is_upload', models.NullBooleanField(default=0, verbose_name='是否允许上传文件')),
                ('is_Auxiliary', models.NullBooleanField(default=0, verbose_name='辅助管理员')),
                ('ip', models.CharField(blank=True, default='', max_length=128, verbose_name='上次登录ip地址')),
                ('ipaddress', models.CharField(blank=True, default='', max_length=128, verbose_name='ip物理地址')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息列表',
                'verbose_name_plural': '用户信息列表',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('attention_id', models.IntegerField(default=0, verbose_name='关注的用户')),
                ('is_attention', models.IntegerField(default=0, verbose_name='是否已关注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '关注信息列表',
                'verbose_name_plural': '关注信息列表',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('dynamic_like', models.IntegerField(blank=True, default=0, verbose_name='点赞次数')),
                ('dynamic_attention', models.IntegerField(blank=True, default=0, verbose_name='关注次数')),
                ('dynamic_search', models.IntegerField(blank=True, default=0, verbose_name='搜索次数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户动态列表',
                'verbose_name_plural': '用户动态列表',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('interest', models.CharField(blank=True, default='', max_length=255, verbose_name='兴趣')),
                ('aims', models.CharField(blank=True, default='', max_length=255, verbose_name='最近目标')),
                ('motto', models.CharField(blank=True, default='', max_length=255, verbose_name='座右铭')),
                ('self_reprot', models.CharField(blank=True, default='', max_length=1024, verbose_name='自我介绍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人信息列表',
                'verbose_name_plural': '个人信息列表',
            },
        ),
        migrations.CreateModel(
            name='UPfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(default='', max_length=256, verbose_name='文件名')),
                ('file', models.CharField(blank=True, default='', max_length=512, verbose_name='文件路径')),
                ('time', models.DateTimeField(auto_now_add=True, max_length=128, verbose_name='时间')),
                ('Prohibited', models.NullBooleanField(default=0, verbose_name='文件是否已删除')),
                ('Prohibited_info', models.CharField(default='', max_length=256, verbose_name='删除信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文件信息列表',
                'verbose_name_plural': '文件信息列表',
            },
        ),
    ]
